### PR TITLE
Update to latest billing sdk 6.0, update gradle and flutter sdk, add some features

### PR DESCRIPTION
**Pull request by offline-first**
- offerTags on SubscriptionOfferAndroid now supported 
- add freeTrialDays on PricingPhaseAndroid
- add periodToDays method
- add priceAmountMicros to PricingPhaseAndroid
- fix: price, formattedPrice and currency is null on oneTime purchase

### CODE REVIEW

**Comment by offline-first** [comment]
How to fix this Flutter CI build issue (update flutter/dart version)?

**Review by hyochan — APPROVED** [review]
Looks like this is what is desperately needed these days 🚀🚀🚀🚀

**Comment by hyochan** [comment]
> How to fix this Flutter CI build issue (update flutter/dart version)?

I'll try to handle this. Sorry for the force-push

**Review by hyochan — CHANGES_REQUESTED** [review]
@offline-first Could you kindly check unit test failing?

**Comment by offline-first** [comment]
@hyochan can you give me a hint how to auto format with Android Studio (Hedgehog). I use `option + command + L`

**Pull request closed without merging**
